#Programming for Data Analysis Project 2019

Peter McGowan
G00190832

In [2]:
# Import numpy to analyse it
# Import matplotlib.pyplot and seaborn for visualisations
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

This is the numpy.random documentation:
https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.random.html

The "Simple Random Data" function generates pseudo-random numbers in the requested format.

In [6]:
# Generate 5 random numbers
np.random.rand(5)

array([0.09452482, 0.73814305, 0.78984517, 0.12916855, 0.35438345])

In [7]:
# Generate a 5x5 array of random numbers
np.random.rand(5,5)

array([[0.98268201, 0.29510889, 0.68921591, 0.35355341, 0.79568276],
       [0.54562307, 0.10721712, 0.55089541, 0.43056156, 0.08693352],
       [0.52223337, 0.68578509, 0.83679089, 0.84293849, 0.00143979],
       [0.11648505, 0.4854669 , 0.95750575, 0.77636588, 0.38271214],
       [0.12330896, 0.88991916, 0.43492106, 0.7593882 , 0.15306849]])

In [8]:
# Generate a 3x3x3 array of random numbers
np.random.rand(3,3,3)

array([[[0.62611147, 0.4548954 , 0.69281657],
        [0.03625446, 0.58484442, 0.38308165],
        [0.04836633, 0.92229166, 0.13281941]],

       [[0.69418526, 0.52040527, 0.72053432],
        [0.17215251, 0.87889681, 0.38218043],
        [0.59461147, 0.52517081, 0.95366354]],

       [[0.59734575, 0.22845854, 0.54730369],
        [0.76819988, 0.08863394, 0.18328316],
        [0.95570367, 0.5620779 , 0.02397447]]])

The "Permutations" function operates differently depending on the input. Giving a single integer will assume the input is a range and output a random permutation of that range.

In [9]:
np.random.permutation(5)

array([4, 3, 2, 0, 1])

In contrast, inputting an array will output a permutation of the input array.

In [12]:
np.random.permutation([5, 4, 3, 2, 1])

array([1, 5, 4, 3, 2])