# Programming for Data Analysis Project 2019

Peter McGowan
G00190832

### Tasks:
1. Explain the overall purpose of the package.
2. Explain the use of the "Simple random data" and "Permutations" functions.
3. Explain the use and purpose of at least five "Distributions" functions.
4. Explain the use of seeds in generating pseudorandom numbers.

Firstly, import some packages for use.
We need numpy for the assignment. We'll also bring in matplotlib and seaborn for creating visualisations.

In [ ]:
# Import numpy to analyse it
# Import matplotlib.pyplot and seaborn for visualisations
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

This is the numpy.random documentation:
https://docs.scipy.org/doc/numpy-1.16.0/reference/routines.random.html

## 1. Explain the overall purpose of the package

From the [NumPy User Manual](https://numpy.org/doc/1.16/user/whatisnumpy.html):

>NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

NumPy is a Python library that extends its abilities to carry out scientific computing.

It consists of a selection of array objects (Python doesn't have inbuilt support for arrays) and a range of algorithms for carrying out operations on arrays. It provides useful routines for statistical analysis and random number generation.

numpy.random is a set of routines that focus on generation of, or working with random numbers. The functions can be split into four categories:
1. Simple random data
2. Permutations
3. Distributions
4. Random generator

## 2. Explain the use of the "Simple random data" and "Permutations" functions.

### Simple Random Data

The "Simple Random Data" function generates pseudo-random numbers in the requested format. It includes 10 routines:
1. [numpy.random.rand](https://docs.scipy.org/doc/numpy-1.16.0/reference/generated/numpy.random.rand.html#numpy.random.rand): Random values in a given shape.
2. [numpy.random.randn](https://docs.scipy.org/doc/numpy-1.16.0/reference/generated/numpy.random.randn.html#numpy.random.randn): Return a sample (or samples) from the “standard normal” distribution.
3. [numpy.random.randint](https://docs.scipy.org/doc/numpy-1.16.0/reference/generated/numpy.random.randint.html#numpy.random.randint): Return random integers from low (inclusive) to high (exclusive).
4. [numpy.random.random_integers](https://docs.scipy.org/doc/numpy-1.16.0/reference/generated/numpy.random.random_integers.html#numpy.random.random_integers): Random integers of type np.int between low and high, inclusive.
5. [numpy.random.random_sample](https://docs.scipy.org/doc/numpy-1.16.0/reference/generated/numpy.random.random_sample.html#numpy.random.random_sample): Return random floats in the half-open interval (0.0, 1.0).
6. [numpy.random.random](https://docs.scipy.org/doc/numpy-1.16.0/reference/generated/numpy.random.random.html#numpy.random.random): Return random floats in the half-open interval (0.0, 1.0).
7. [numpy.random.ranf](https://docs.scipy.org/doc/numpy-1.16.0/reference/generated/numpy.random.ranf.html#numpy.random.ranf): Return random floats in the half-open interval (0.0, 1.0).
8. [numpy.random.sample](https://docs.scipy.org/doc/numpy-1.16.0/reference/generated/numpy.random.sample.html#numpy.random.sample): Return random floats in the half-open interval (0.0, 1.0).
9. [numpy.random.choice](https://docs.scipy.org/doc/numpy-1.16.0/reference/generated/numpy.random.choice.html#numpy.random.choice): Generates a random sample from a given 1-D array
10. [numpy.random.bytes](https://docs.scipy.org/doc/numpy-1.16.0/reference/generated/numpy.random.bytes.html#numpy.random.bytes): Return random bytes.

(No.s 6 through 8 are identical in function and output https://stackoverflow.com/questions/18829185/difference-between-various-numpy-random-functions)

#### Rand (numpy.random.rand)

#### Randn (numpy.random.randn)

#### Randint (numpy.random.randint)

#### Random_integers (numpy.random.random_integers)

#### Random_sample (numpy.random.random_sample)

#### Random (numpy.random.random/ numpy.random.ranf/ numpy.random.sample)

#### Choice (numpy.random.choice)

#### Bytes (numpy.random.bytes)

In [6]:
# Generate 5 random numbers
np.random.rand(5)

array([0.09452482, 0.73814305, 0.78984517, 0.12916855, 0.35438345])

In [7]:
# Generate a 5x5 array of random numbers
np.random.rand(5,5)

array([[0.98268201, 0.29510889, 0.68921591, 0.35355341, 0.79568276],
       [0.54562307, 0.10721712, 0.55089541, 0.43056156, 0.08693352],
       [0.52223337, 0.68578509, 0.83679089, 0.84293849, 0.00143979],
       [0.11648505, 0.4854669 , 0.95750575, 0.77636588, 0.38271214],
       [0.12330896, 0.88991916, 0.43492106, 0.7593882 , 0.15306849]])

In [8]:
# Generate a 3x3x3 array of random numbers
np.random.rand(3,3,3)

array([[[0.62611147, 0.4548954 , 0.69281657],
        [0.03625446, 0.58484442, 0.38308165],
        [0.04836633, 0.92229166, 0.13281941]],

       [[0.69418526, 0.52040527, 0.72053432],
        [0.17215251, 0.87889681, 0.38218043],
        [0.59461147, 0.52517081, 0.95366354]],

       [[0.59734575, 0.22845854, 0.54730369],
        [0.76819988, 0.08863394, 0.18328316],
        [0.95570367, 0.5620779 , 0.02397447]]])

### Permutations

There are two functions in the Permutations category:
1. [numpy.random.shuffle](https://docs.scipy.org/doc/numpy-1.16.0/reference/generated/numpy.random.shuffle.html#numpy.random.shuffle): Modify a sequence in-place by shuffling its contents.
2. [numpy.random.permutations](https://docs.scipy.org/doc/numpy-1.16.0/reference/generated/numpy.random.permutation.html#numpy.random.permutation):  Randomly permute a sequence, or return a permuted range.

#### Shuffle (numpy.random.shuffle)

#### Permutations (numpy.random.permutations)

The "Permutations" function operates differently depending on the input. Giving a single integer will assume the input is a range and output a random permutation of that range.

In [9]:
np.random.permutation(5)

array([4, 3, 2, 0, 1])

In contrast, inputting an array will output a permutation of the input array.

In [12]:
np.random.permutation([5, 4, 3, 2, 1])

array([1, 5, 4, 3, 2])

## 3. Explain the use and purpose of at least five "Distributions" functions.

We will look in detail at the following 5 Distributions function:
1. [numpy.random.binomial](https://docs.scipy.org/doc/numpy-1.16.0/reference/generated/numpy.random.binomial.html#numpy.random.binomial)
2. [numpy.random.laplace](https://docs.scipy.org/doc/numpy-1.16.0/reference/generated/numpy.random.laplace.html#numpy.random.laplace)
3. [numpy.random.normal](https://docs.scipy.org/doc/numpy-1.16.0/reference/generated/numpy.random.normal.html#numpy.random.normal)
4. [numpy.random.poisson](https://docs.scipy.org/doc/numpy-1.16.0/reference/generated/numpy.random.poisson.html#numpy.random.poisson)
5. [numpy.random.uniform](https://docs.scipy.org/doc/numpy-1.16.0/reference/generated/numpy.random.uniform.html#numpy.random.uniform)

### Bionmial (numpy.random.binomial)

### Laplace (numpy.random.laplace)

### Normal (numpy.random.normal)

### Poisson (numpy.random.poisson)

### Uniform (numpy.random.uniform)

## 4. Explain the use of seeds in generating pseudorandom numbers.